name: URLChecker
on: 
  schedule:
  - cron: '12 15 22 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: urls-checker
      uses: urlstechie/urlchecker-action@master
      with: 
        file_types: .md
        include_files: README.md